import turtle
turtle.showturtle()

turtle.penup()
turtle.forward(50)
turtle.left(180)
turtle.pendown()
turtle.forward(100)
turtle.penup()
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.pendown()
turtle.forward(100)
turtle.done()
