import turtle
turtle.showturtle()

turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.circle(50)
turtle.right(180)
turtle.circle(50)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.circle(50)
turtle.right(180)
turtle.circle(50)
turtle.done()